#!/bin/bash

if [ "$#" == "4" ]; then
    if [[ "$1" == "-p" && "$3" == "-n" ]]; then
		python dnsserver.py $2 $4
	else
		echo "DNS Wrong parameters!!"
	fi
else
    echo "Please provide correct parameters"
    exit
fi
